name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 🚨 Breaking changes
    labels:
      - major
  - title: ✨ Nuove funzionalità
    labels:
      - minor
  - title: 🐛 Correzioni
    labels:
      - patch
      
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
default: patch

template: |  
  ## Modifiche

  $CHANGES

  ## Altre modifiche

  $UNCATEGORIZED_CHANGES
  
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
