name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - major

  minor:
    labels:
      - minor

  patch:
    labels:
      - patch

default: patch

change-template: '- $TITLE (#$NUMBER)'

template: |
  ## Modifiche
  
  $CHANGES

categories:
  - title: 🚨 Breaking changes
    labels:
      - major

  - title: ✨ Nuove funzionalità
    labels:
      - minor

  - title: 🐛 Correzioni
    labels:
      - patch

exclude-labels:
  - skip-changelog
